const translations = {
  en: {
    "Ethiopian Crafts": "Ethiopian Crafts",
    "Home": "Home",
    "Products": "Products",
    "Cart": "Cart",
    "Login": "Login",
    "Logout": "Logout",
    "Welcome to Ethiopian Traditional Craft E-commerce": "Welcome to Ethiopian Traditional Craft E-commerce",
    "Discover unique, handcrafted Ethiopian products and bring the beauty of Ethiopian culture into your home.": "Discover unique, handcrafted Ethiopian products and bring the beauty of Ethiopian culture into your home.",
    "Explore Products": "Explore Products",
    // ProductList
    "Filters": "Filters",
    "Search Product": "Search Product",
    "Search by name...": "Search by name...",
    "Price Range": "Price Range",
    "Min Price": "Min Price",
    "Max Price": "Max Price",
    "Price Slider": "Price Slider",
    "Category": "Category",
    "All Categories": "All Categories",
    "Reset Filters": "Reset Filters",
    "Product List": "Product List",
    "Loading products...": "Loading products...",
    "Failed to fetch products.": "Failed to fetch products.",
    "Retry": "Retry",
    "Product Image": "Product Image",
    "Unnamed Product": "Unnamed Product",
    "Price unavailable": "Price unavailable",
    "No products match your search.": "No products match your search.",
    // Cart
    "🛒 Your Shopping Cart": "🛒 Your Shopping Cart",
    "Your cart is empty.": "Your cart is empty.",
    "🛍️ Start Shopping": "🛍️ Start Shopping",
    "each": "each",
    "Stock Remaining": "Stock Remaining",
    "Cart Summary": "Cart Summary",
    "Subtotal": "Subtotal",
    "Total": "Total",
    "Processing...": "Processing...",
    "✅ Proceed to Checkout": "✅ Proceed to Checkout",
    "Maximum available stock is": "Maximum available stock is",
    // Checkout
    "💳 Checkout": "💳 Checkout",
    "Enter Payment Details": "Enter Payment Details",
    "Email": "Email",
    "Enter your email": "Enter your email",
    "First Name": "First Name",
    "Enter your first name": "Enter your first name",
    "Last Name": "Last Name",
    "Enter your last name": "Enter your last name",
    "Full Name": "Full Name",
    "Enter your full name": "Enter your full name",
    "Phone Number": "Phone Number",
    "Enter your phone number": "Enter your phone number",
    "💳 Pay with Chapa": "💳 Pay with Chapa",
    "Submit Payment": "Submit Payment",
    "Cancel": "Cancel",
    "Cart is empty. Add items before checkout.": "Cart is empty. Add items before checkout.",
    // Login
    "Welcome Back 👋": "Welcome Back 👋",
    "Sign in to access your personalized shopping experience": "Sign in to access your personalized shopping experience",
    "Email Address": "Email Address",
    "your.email@example.com": "your.email@example.com",
    "Password": "Password",
    "Logging in...": "Logging in...",
    "Login failed. Please try again.": "Login failed. Please try again.",
    "Session verification failed: No role found.": "Session verification failed: No role found.",
    "Failed to verify session. Please try logging in again.": "Failed to verify session. Please try logging in again.",
    "Don't have an account?": "Don't have an account?",
    "Sign Up": "Sign Up",
    // Signup
    "Create Your Account 🌟": "Create Your Account 🌟",
    "I am a:": "I am a:",
    "Customer": "Customer",
    "Artisan": "Artisan",
    "Password Strength:": "Password Strength:",
    "Strong ✅": "Strong ✅",
    "Medium ⚠️": "Medium ⚠️",
    "Weak ❌": "Weak ❌",
    "Password must meet all security requirements.": "Password must meet all security requirements.",
    "Phone number must be exactly 10 digits.": "Phone number must be exactly 10 digits.",
    "Your password is too weak. Please use a stronger password.": "Your password is too weak. Please use a stronger password.",
    "Signing Up...": "Signing Up...",
    "Signup successful! Please log in.": "Signup successful! Please log in.",
    "Signup failed. Please try again.": "Signup failed. Please try again.",
    "Already have an account?": "Already have an account?",
    "Shop Name": "Shop Name",
    // Footer
    "Ethiopian Traditional Crafts": "Ethiopian Traditional Crafts",
    "All rights reserved.": "All rights reserved.",
    "About Us": "About Us",
    "Contact": "Contact",
    // Admin App
    "404: Admin Page Not Found": "404: Admin Page Not Found",
    // Admin Dashboard
    "Admin Dashboard": "Admin Dashboard",
    "Welcome to the Admin Dashboard! Below are key statistics about the platform.": "Welcome to the Admin Dashboard! Below are key statistics about the platform.",
    "Loading statistics...": "Loading statistics...",
    "Failed to fetch statistics.": "Failed to fetch statistics.",
    "Total Products": "Total Products",
    "Total Orders": "Total Orders",
    "Total Users": "Total Users",
    // Admin Navbar
    "Admin Panel": "Admin Panel",
    "Dashboard": "Dashboard",
    "Orders": "Orders",
    "Users": "Users",
    "View Comments": "View Comments",
    "Profile": "Profile",
    // Admin Orders
    "Admin Orders": "Admin Orders",
    "Loading orders...": "Loading orders...",
    "Failed to fetch orders.": "Failed to fetch orders.",
    "Order ID": "Order ID",
    "Customer": "Customer",
    "Artisan": "Artisan",
    "Status": "Status",
    "Order Date": "Order Date",
    "Actions": "Actions",
    "Unknown Customer": "Unknown Customer",
    "Unknown Artisan": "Unknown Artisan",
    "No orders found.": "No orders found.",
    "Pending": "Pending",
    "Shipped": "Shipped",
    "Delivered": "Delivered",
    "Cancelled": "Cancelled",
    "Are you sure you want to change the status to": "Are you sure you want to change the status to",
    "Failed to update order status.": "Failed to update order status.",
    // Admin Products
    "Admin Products": "Admin Products",
    "Image": "Image",
    "Product Name": "Product Name",
    "Price": "Price",
    "Stock": "Stock",
    "No products found.": "No products found.",
    "Delete": "Delete",
    "Are you sure you want to delete this product?": "Are you sure you want to delete this product?",
    "Failed to delete product.": "Failed to delete product.",
    // Admin Profile
    "Admin Profile & Settings": "Admin Profile & Settings",
    "Loading profile...": "Loading profile...",
    "Failed to fetch profile.": "Failed to fetch profile.",
    "Profile Information": "Profile Information",
    "Name": "Name",
    "Not set": "Not set",
    "Edit Profile": "Edit Profile",
    "Save Changes": "Save Changes",
    "Change Password": "Change Password",
    "Current Password": "Current Password",
    "New Password": "New Password",
    "Confirm New Password": "Confirm New Password",
    "Updating...": "Updating...",
    "Update Password": "Update Password",
    "Failed to update profile.": "Failed to update profile.",
    "Phone number must be exactly 10 digits and contain only numbers.": "Phone number must be exactly 10 digits and contain only numbers.",
    "Password must be at least 8 characters, with at least one uppercase letter, one lowercase letter, one number, and one special character (e.g., !@#$%^&*).": "Password must be at least 8 characters, with at least one uppercase letter, one lowercase letter, one number, and one special character (e.g., !@#$%^&*).",
    "New password and confirm password do not match.": "New password and confirm password do not match.",
    "Failed to update password.": "Failed to update password.",
    "Password updated successfully!": "Password updated successfully!",
    // Admin Users
    "Admin Users": "Admin Users",
    "Loading users and artisans...": "Loading users and artisans...",
    "Failed to fetch users and artisans. Please ensure you are logged in as an admin.": "Failed to fetch users and artisans. Please ensure you are logged in as an admin.",
    "Customers": "Customers",
    "Artisans": "Artisans",
    "No customers found.": "No customers found.",
    "No artisans found.": "No artisans found.",
    "Active": "Active",
    "Inactive": "Inactive",
    "Deactivate": "Deactivate",
    "Activate": "Activate",
    "Please log in as an admin to access this page.": "Please log in as an admin to access this page.",
    "Are you sure you want to mark this": "Are you sure you want to mark this",
    "as": "as",
    "Failed to toggle user status.": "Failed to toggle user status.",
    "Failed to toggle artisan status.": "Failed to toggle artisan status.",
    // AddProduct
    "Add New Product": "Add New Product",
    "Name": "Name",
    "Price (in Br)": "Price (in Br)",
    "Description": "Description",
    "Category": "Category",
    "Stock": "Stock",
    "Image": "Image",
    "Adding Product...": "Adding Product...",
    "Add Product": "Add Product",
    "Select a category": "Select a category",
    "All fields are required.": "All fields are required.",
    "Price must be a positive number.": "Price must be a positive number.",
    "Stock cannot be negative.": "Stock cannot be negative.",
    "Please upload a valid image (JPEG, PNG, or GIF).": "Please upload a valid image (JPEG, PNG, or GIF).",
    "Session expired. Please log in again.": "Session expired. Please log in again.",
    "Failed to insert product": "Failed to insert product",
    "Product added successfully!": "Product added successfully!",
    // ProductManagement
    "Product Management": "Product Management",
    "Edit Product": "Edit Product",
    "Update Product": "Update Product",
    "Updating Product...": "Updating Product...",
    "Image (optional)": "Image (optional)",
    "Please fill in all required fields.": "Please fill in all required fields.",
    "Failed to add product. Please log in.": "Failed to add product. Please log in.",
    "Failed to delete product. Please log in.": "Failed to delete product. Please log in.",
    "Failed to update product. Please log in.": "Failed to update product. Please log in.",
    "Please log in as an artisan to access this page.": "Please log in as an artisan to access this page.",
    "Go to Login": "Go to Login",
    // OrderManagement
    "Order Management": "Order Management",
    "Filter by Status:": "Filter by Status:",
    "All": "All",
    "Pending": "Pending",
    "Shipped": "Shipped",
    "Delivered": "Delivered",
    "Cancelled": "Cancelled",
    "Customer": "Customer",
    "Total": "Total",
    "Order Date": "Order Date",
    "Actions": "Actions",
    "Unknown Customer": "Unknown Customer",
    "No orders found.": "No orders found.",
    "Order Details": "Order Details",
    "Order ID": "Order ID",
    "Date": "Date",
    "Products": "Products",
    "Close": "Close",
    "Cancel": "Cancel",
    "Ship": "Ship",
    "Deliver": "Deliver",
    "Failed to fetch orders. Please try again.": "Failed to fetch orders. Please try again.",
    "Order not found or you don’t have permission to update it.": "Order not found or you don’t have permission to update it.",
    "Failed to update order status.": "Failed to update order status.",
    // NavbarArtisan
    "Artisan Portal": "Artisan Portal",
    // ArtisanProfile
    "Artisan Profile": "Artisan Profile",
    "Bio": "Bio",
    "Tell us about yourself...": "Tell us about yourself...",
    "Save": "Save",
    "No bio provided": "No bio provided",
    // ArtisanDashboard
    "Artisan Dashboard": "Artisan Dashboard",
    "Sales Today": "Sales Today",
    "Manage Products": "Manage Products",
    "View Orders": "View Orders",
    "Failed to fetch dashboard stats. Please log in.": "Failed to fetch dashboard stats. Please log in.",
    // ArtisanComments
    "Comments on My Products": "Comments on My Products",
    "Comment": "Comment",
    "Product": "Product",
    "Product Deleted": "Product Deleted",
    "No comments found.": "No comments found.",
    "Failed to fetch comments.": "Failed to fetch comments.",
    "404: Page Not Found": "404: Page Not Found",
    "Comment Details": "Comment Details",
    "Loading...": "Loading...",
    "Failed to fetch comment details.": "Failed to fetch comment details.",
    "Back to Comments": "Back to Comments",
    "Comment": "Comment",
    "Product": "Product",
    "Deleted Product": "Deleted Product",
    "Date": "Date",
    "Invalid comment ID. Please select a valid comment.": "Invalid comment ID. Please select a valid comment.",
    "My Comments": "My Comments",
    "Add New Comment": "Add New Comment",
    "Loading comments...": "Loading comments...",
    "Please log in as a customer to view your comments.": "Please log in as a customer to view your comments.",
    "Please log in to view your comments.": "Please log in to view your comments.",
    "Retry": "Retry",
    "Go to Login": "Go to Login",
    "Failed to fetch comments. Please ensure you are logged in.": "Failed to fetch comments. Please ensure you are logged in.",
    "Actions": "Actions",
    "View Details": "View Details",
    "Deleting...": "Deleting...",
    "No comments found. Add one to get started!": "No comments found. Add one to get started!",
    "Select Product": "Select Product",
    "Select a product": "Select a product",
    "Loading products...": "Loading products...",
    "Failed to fetch products for commenting.": "Failed to fetch products for commenting.",
    "No products available to comment on. Purchase something first!": "No products available to comment on. Purchase something first!",
    "e.g., 'I need more of it'": "e.g., 'I need more of it'",
    "Cancel": "Cancel",
    "Submitting...": "Submitting...",
    "Please select a product.": "Please select a product.",
    "Please enter a comment.": "Please enter a comment.",
    "Failed to add comment. Please try again.": "Failed to add comment. Please try again.",
    "Authentication failed. Please log in again.": "Authentication failed. Please log in again.",
    "Are you sure you want to delete this comment?": "Are you sure you want to delete this comment?",
    "Failed to delete comment.": "Failed to delete comment.",
    "Customer Dashboard": "Customer Dashboard",
    "Loading dashboard...": "Loading dashboard...",
    "Failed to load dashboard data. Please log in.": "Failed to load dashboard data. Please log in.",
    "Welcome back": "Welcome back",
    "Customer": "Customer",
    "Here’s what’s happening with your account.": "Here’s what’s happening with your account.",
    "Recent Orders": "Recent Orders",
    "Orders in the last 7 days": "Orders in the last 7 days",
    "View All Orders": "View All Orders",
    "Profile": "Profile",
    "Manage your personal details": "Manage your personal details",
    "Edit Profile": "Edit Profile",
    "Quick Actions": "Quick Actions",
    "Shop Now": "Shop Now",
    "View Cart": "View Cart",
    "Order Details": "Order Details",
    "Loading order details...": "Loading order details...",
    "Failed to fetch order details. Please try again.": "Failed to fetch order details. Please try again.",
    "Back to Orders": "Back to Orders",
    "Order": "Order",
    "Total Amount": "Total Amount",
    "Order Status": "Order Status",
    "Payment Status": "Payment Status",
    "Order Date": "Order Date",
    "Customer Information": "Customer Information",
    "Email": "Email",
    "Name": "Name",
    "Phone": "Phone",
    "Products": "Products",
    "Product Name": "Product Name",
    "Price": "Price",
    "Quantity": "Quantity",
    "Total": "Total",
    "Pay Now": "Pay Now",
    "Pending": "Pending",
    "Shipped": "Shipped",
    "Cancelled": "Cancelled",
    "Success": "Success",
    "Failed": "Failed",
    "Your Orders": "Your Orders",
    "Loading orders...": "Loading orders...",
    "Failed to fetch orders. Please log in.": "Failed to fetch orders. Please log in.",
    "Order ID": "Order ID",
    "No orders found.": "No orders found.",
    "Customer Profile": "Customer Profile",
    "Loading profile...": "Loading profile...",
    "Failed to fetch profile. Please log in.": "Failed to fetch profile. Please log in.",
    "Profile Information": "Profile Information",
    "Phone Number": "Phone Number",
    "Not set": "Not set",
    "Change Password": "Change Password",
    "Current Password": "Current Password",
    "New Password": "New Password",
    "Confirm New Password": "Confirm New Password",
    "Update Password": "Update Password",
    "Updating...": "Updating...",
    "Failed to update profile. Please log in.": "Failed to update profile. Please log in.",
    "Save": "Save",
    "Saving...": "Saving...",
    "Phone number must be exactly 10 digits and contain only numbers.": "Phone number must be exactly 10 digits and contain only numbers.",
    "Password must be at least 8 characters, with at least one uppercase letter, one lowercase letter, one number, and one special character (e.g., !@#$%^&*).": "Password must be at least 8 characters, with at least one uppercase letter, one lowercase letter, one number, and one special character (e.g., !@#$%^&*).",
    "New password and confirm password do not match.": "New password and confirm password do not match.",
    "Failed to update password.": "Failed to update password.",
    "Password updated successfully!": "Password updated successfully!",
    "Customer Portal": "Customer Portal",
    "Dashboard": "Dashboard",
    "Shop": "Shop",
    "Cart": "Cart",
    "Orders": "Orders",
    "Comments": "Comments",
    "Logout": "Logout"
  },
  am: {
    "Ethiopian Crafts": "የኢትዮጵያ የእጅ ሥራዎች",
    "Home": "መነሻ",
    "Products": "ምርቶች",
    "Cart": "ጋሪ",
    "Login": "መግባት",
    "Logout": "መውጣት",
    "Welcome to Ethiopian Traditional Craft E-commerce": "እንኳን ወደ ኢትዮጵያ ባህላዊ የእጅ ሥራ ኢኮሜርስ ተቀበሉ",
    "Discover unique, handcrafted Ethiopian products and bring the beauty of Ethiopian culture into your home.": "የተለያዩ በእጅ የተሰሩ የኢትዮጵያ ምርቶችን ያስሱ እና የኢትዮጵያ ባህል ውበት ወደ ቤትዎ ያምጡ።",
    "Explore Products": "ምርቶችን ያስሱ",
    // ProductList
    "Filters": "ማጣሪያዎች",
    "Search Product": "ምርት ፈልግ",
    "Search by name...": "በስም ፈልግ...",
    "Price Range": "የዋጋ ክልል",
    "Min Price": "ዝቅተኛ ዋጋ",
    "Max Price": "ከፍተኛ ዋጋ",
    "Price Slider": "የዋጋ ተንሸራታች",
    "Category": "ምድብ",
    "All Categories": "ሁሉም ምድቦች",
    "Reset Filters": "ማጣሪያዎችን እንደገና አስጀምር",
    "Product List": "የምርት ዝርዝር",
    "Loading products...": "ምርቶችን በመጫን ላይ...",
    "Failed to fetch products.": "ምርቶችን መጫን አልተሳካም።",
    "Retry": "እንደገና ሞክር",
    "Product Image": "የምርት ምስል",
    "Unnamed Product": "ስም የሌለው ምርት",
    "Price unavailable": "ዋጋ አይገኝም",
    "No products match your search.": "የፍለጋዎ ምርቶች አልተገኙም።",
    // Cart
    "🛒 Your Shopping Cart": "🛒 የእርስዎ የግብይት ጋሪ",
    "Your cart is empty.": "የእርስዎ ጋሪ ባዶ ነው።",
    "🛍️ Start Shopping": "🛍️ ግብይት ይጀምሩ",
    "each": "እያንዳንዱ",
    "Stock Remaining": "ቀሪ ክምችት",
    "Cart Summary": "የጋሪ ማጠቃለያ",
    "Subtotal": "ንዑስ ድምር",
    "Total": "ድምር",
    "Processing...": "በሂደት ላይ...",
    "✅ Proceed to Checkout": "✅ ወደ መፈተሻ ይቀጥሉ",
    "Maximum available stock is": "ከፍተኛው የሚገኝ ክምችት",
    // Checkout
    "💳 Checkout": "💳 መፈተሻ",
    "Enter Payment Details": "የክፍያ ዝርዝሮችን ያስገቡ",
    "Email": "ኢሜይል",
    "Enter your email": "የእርስዎን ኢሜይል ያስገቡ",
    "First Name": "ስም",
    "Enter your first name": "የእርስዎን ስም ያስገቡ",
    "Last Name": "የአባት ስም",
    "Enter your last name": "የእርስዎን የአባት ስም ያስገቡ",
    "Full Name": "ሙሉ ስም",
    "Enter your full name": "ሙሉ ስምዎን ያስገቡ",
    "Phone Number": "ስልክ ቁጥር",
    "Enter your phone number": "የእርስዎን ስልክ ቁጥር ያስገቡ",
    "💳 Pay with Chapa": "💳 በቻፓ ይክፈሉ",
    "Submit Payment": "ክፍያ ያስገቡ",
    "Cancel": "መሰረዝ",
    "Cart is empty. Add items before checkout.": "ጋሪው ባዶ ነው። እቃዎችን ይጨምሩ።",
    // Login
    "Welcome Back 👋": "እንኳን ደህና መጡ 👋",
    "Sign in to access your personalized shopping experience": "ለግል የተበጀ የግብይት ተሞክሮ ለመድረስ ይግቡ",
    "Email Address": "የኢሜይል አድራሻ",
    "your.email@example.com": "የእርስዎ.ኢሜይል@ምሳሌ.com",
    "Password": "የይለፍ ቃል",
    "Logging in...": "በመግባት ላይ...",
    "Login failed. Please try again.": "መግባት አልተሳካም። እባክዎ እንደገና ይሞክሩ።",
    "Session verification failed: No role found.": "የክፍለ ጊዜ ማረጋገጫ አልተሳካም፡ ምንም ሚና አልተገኘም።",
    "Failed to verify session. Please try logging in again.": "ክፍለ ጊዜን ማረጋገጥ አልተሳካም። እባክዎ እንደገና መግባት ይሞክሩ።",
    "Don't have an account?": "መለያ የለዎትም?",
    "Sign Up": "መመዝገብ",
    // Signup
    "Create Your Account 🌟": "መለያዎን ይፍጠሩ 🌟",
    "I am a:": "እኔ ነኝ፡",
    "Customer": "ደንበኛ",
    "Artisan": "እጅ ጥበብ ባለሙያ",
    "Password Strength:": "የይለፍ ቃል ጥንካሬ፡",
    "Strong ✅": "ጠንካራ ✅",
    "Medium ⚠️": "መካከለኛ ⚠️",
    "Weak ❌": "ደካማ ❌",
    "Password must meet all security requirements.": "የይለፍ ቃል ሁሉንም የደህንነት መስፈርቶች መፈጸም አለበት።",
    "Phone number must be exactly 10 digits.": "ስልክ ቁጥር በትክክል 10 አሃዞች መሆን አለበት።",
    "Your password is too weak. Please use a stronger password.": "የእርስዎ የይለፍ ቃል በጣም ደካማ ነው። እባክዎ ጠንካራ የይለፍ ቃል ይጠቀሙ።",
    "Signing Up...": "በመመዝገብ ላይ...",
    "Signup successful! Please log in.": "መመዝገብ ተሳክቷል! እባክዎ ይግቡ።",
    "Signup failed. Please try again.": "መመዝገብ አልተሳካም። እባክዎ እንደገና ይሞክሩ።",
    "Already have an account?": "መለያ አለዎት?",
    "Shop Name": "የሱቅ ስም",
    // Footer
    "Ethiopian Traditional Crafts": "የኢትዮጵያ ባህላዊ የእጅ ሥራዎች",
    "All rights reserved.": "ሁሉም መብቶች የተጠበቁ ናቸው።",
    "About Us": "ስለ እኛ",
    "Contact": "ያግኙን",
    // Admin App
    "404: Admin Page Not Found": "404: የአስተዳዳሪ ገፅ አልተገኘም",
    // Admin Dashboard
    "Admin Dashboard": "የአስተዳዳሪ መቆጣጠሪያ",
    "Welcome to the Admin Dashboard! Below are key statistics about the platform.": "እንኳን ወደ አስተዳዳሪ መቆጣጠሪያ ተቀበሉ! ከዚህ በታች ስለ መድረኩ ቁልፍ መረጃዎች አሉ።",
    "Loading statistics...": "መረጃዎችን በመጫን ላይ...",
    "Failed to fetch statistics.": "መረጃዎችን መጫን አልተሳካም።",
    "Total Products": "ጠቅላላ ምርቶች",
    "Total Orders": "ጠቅላላ ትዕዛዞች",
    "Total Users": "ጠቅላላ ተጠቃሚዎች",
    // Admin Navbar
    "Admin Panel": "የአስተዳዳሪ ፓነል",
    "Dashboard": "መቆጣጠሪያ",
    "Orders": "ትዕዛዞች",
    "Users": "ተጠቃሚዎች",
    "View Comments": "አስተያየቶችን ይመልከቱ",
    "Profile": "መገለጫ",
    // Admin Orders
    "Admin Orders": "የአስተዳዳሪ ትዕዛዞች",
    "Loading orders...": "ትዕዛዞችን በመጫን ላይ...",
    "Failed to fetch orders.": "ትዕዛዞችን መጫን አልተሳካም።",
    "Order ID": "የትዕዛዝ መለያ",
    "Customer": "ደንበኛ",
    "Artisan": "እጅ ጥበብ ባለሙያ",
    "Status": "ሁኔታ",
    "Order Date": "የትዕዛዝ ቀን",
    "Actions": "ተግባራት",
    "Unknown Customer": "ያልታወቀ ደንበኛ",
    "Unknown Artisan": "ያልታወቀ እጅ ጥበብ ባለሙያ",
    "No orders found.": "ምንም ትዕዛዞች አልተገኙም።",
    "Pending": "በመጠባበቅ ላይ",
    "Shipped": "ተልኳል",
    "Delivered": "ደርሷል",
    "Cancelled": "ተሰርዟል",
    "Are you sure you want to change the status to": "ሁኔታውን ወደ",
    "Failed to update order status.": "የትዕዛዝ ሁኔታን መዘመን አልተሳካም።",
    // Admin Products
    "Admin Products": "የአስተዳዳሪ ምርቶች",
    "Image": "ምስል",
    "Product Name": "የምርት ስም",
    "Price": "ዋጋ",
    "Stock": "ክምችት",
    "No products found.": "ምንም ምርቶች አልተገኙም።",
    "Delete": "መሰረዝ",
    "Are you sure you want to delete this product?": "ይህን ምርት መሰረዝ እንደሚፈልጉ እርግጠኛ ነዎት?",
    "Failed to delete product.": "ምርትን መሰረዝ አልተሳካም።",
    // Admin Profile
    "Admin Profile & Settings": "የአስተዳዳሪ መገለጫ እና ቅንብሮች",
    "Loading profile...": "መገለጫን በመጫን ላይ...",
    "Failed to fetch profile.": "መገለጫን መጫን አልተሳካም።",
    "Profile Information": "የመገለጫ መረጃ",
    "Name": "ስም",
    "Not set": "አልተዘጋጀም",
    "Edit Profile": "መገለጫ አርትዕ",
    "Save Changes": "ለውጦችን ያስቀምጡ",
    "Change Password": "የይለፍ ቃል ይቀይሩ",
    "Current Password": "የአሁኑ የይለፍ ቃል",
    "New Password": "አዲስ የይለፍ ቃል",
    "Confirm New Password": "አዲሱን የይለፍ ቃል ያረጋግጡ",
    "Updating...": "በመዘመን ላይ...",
    "Update Password": "የይለፍ ቃል ያዘምኑ",
    "Failed to update profile.": "መገለጫን መዘመን አልተሳካም።",
    "Phone number must be exactly 10 digits and contain only numbers.": "ስልክ ቁጥር በትክክል 10 አሃዞች መሆን አለበት እና ቁጥሮችን ብቻ መያዝ አለበት።",
    "Password must be at least 8 characters, with at least one uppercase letter, one lowercase letter, one number, and one special character (e.g., !@#$%^&*).": "የይለፍ ቃል ቢያንስ 8 ቁምፊዎች መሆን አለበት፣ ቢያንስ አንድ ትልቅ ፊደል፣ አንድ ትንሽ ፊደል፣ አንድ ቁጥር፣ እና አንድ ልዩ ቁምፊ (ለምሳሌ፣ !@#$%^&*) መያዝ አለበት።",
    "New password and confirm password do not match.": "አዲስ የይለፍ ቃል እና የተረጋገጠ የይለፍ ቃል አይዛመዱም።",
    "Failed to update password.": "የይለፍ ቃል መዘመን አልተሳካም።",
    "Password updated successfully!": "የይለፍ ቃል በተሳካ ሁኔታ ተዘምኗል!",
    // Admin Users
    "Admin Users": "የአስተዳዳሪ ተጠቃሚዎች",
    "Loading users and artisans...": "ተጠቃሚዎችን እና እጅ ጥበብ ባለሙያዎችን በመጫን ላይ...",
    "Failed to fetch users and artisans. Please ensure you are logged in as an admin.": "ተጠቃሚዎችን እና እጅ ጥበብ ባለሙያዎችን መጫን አልተሳካም። እባክዎ እንደ አስተዳዳሪ መግባትዎን ያረጋግጡ።",
    "Customers": "ደንበኞች",
    "Artisans": "እጅ ጥበብ ባለሙያዎች",
    "No customers found.": "ምንም ደንበኞች አልተገኙም።",
    "No artisans found.": "ምንም እጅ ጥበብ ባለሙያዎች አልተገኙም።",
    "Active": "ንቁ",
    "Inactive": "እንቅስቃሴ-አልባ",
    "Deactivate": "እንቅስቃሴ-አልባ አድርግ",
    "Activate": "ንቁ አድርግ",
    "Please log in as an admin to access this page.": "እባክዎ ይህን ገፅ ለመድረስ እንደ አስተዳዳሪ ይግቡ።",
    "Are you sure you want to mark this": "ይህን መለያ መጠን እንደሚፈልጉ እርግጠኛ ነዎት",
    "as": "እንደ",
    "Failed to toggle user status.": "የተጠቃሚ ሁኔታን መቀያየር አልተሳካም።",
    "Failed to toggle artisan status.": "የእጅ ጥበብ ባለሙያ ሁኔታን መቀያየር አልተሳካም።",
    // AddProduct
    "Add New Product": "Add New Product",
    "Name": "Name",
    "Price (in Br)": "Price (in Br)",
    "Description": "Description",
    "Category": "Category",
    "Stock": "Stock",
    "Image": "Image",
    "Adding Product...": "Adding Product...",
    "Add Product": "Add Product",
    "Select a category": "Select a category",
    "All fields are required.": "All fields are required.",
    "Price must be a positive number.": "Price must be a positive number.",
    "Stock cannot be negative.": "Stock cannot be negative.",
    "Please upload a valid image (JPEG, PNG, or GIF).": "Please upload a valid image (JPEG, PNG, or GIF).",
    "Session expired. Please log in again.": "Session expired. Please log in again.",
    "Failed to insert product": "Failed to insert product",
    "Product added successfully!": "Product added successfully!",
    // ProductManagement
    "Product Management": "Product Management",
    "Edit Product": "Edit Product",
    "Update Product": "Update Product",
    "Updating Product...": "Updating Product...",
    "Image (optional)": "Image (optional)",
    "Please fill in all required fields.": "Please fill in all required fields.",
    "Failed to add product. Please log in.": "Failed to add product. Please log in.",
    "Failed to delete product. Please log in.": "Failed to delete product. Please log in.",
    "Failed to update product. Please log in.": "Failed to update product. Please log in.",
    "Please log in as an artisan to access this page.": "Please log in as an artisan to access this page.",
    "Go to Login": "Go to Login",
    // OrderManagement
    "Order Management": "Order Management",
    "Filter by Status:": "Filter by Status:",
    "All": "All",
    "Pending": "Pending",
    "Shipped": "Shipped",
    "Delivered": "Delivered",
    "Cancelled": "Cancelled",
    "Customer": "Customer",
    "Total": "Total",
    "Order Date": "Order Date",
    "Actions": "Actions",
    "Unknown Customer": "Unknown Customer",
    "No orders found.": "No orders found.",
    "Order Details": "Order Details",
    "Order ID": "Order ID",
    "Date": "Date",
    "Products": "Products",
    "Close": "Close",
    "Cancel": "Cancel",
    "Ship": "Ship",
    "Deliver": "Deliver",
    "Failed to fetch orders. Please try again.": "Failed to fetch orders. Please try again.",
    "Order not found or you don’t have permission to update it.": "Order not found or you don’t have permission to update it.",
    "Failed to update order status.": "Failed to update order status.",
    // NavbarArtisan
    "Artisan Portal": "Artisan Portal",
    // ArtisanProfile
    "Artisan Profile": "Artisan Profile",
    "Bio": "Bio",
    "Tell us about yourself...": "Tell us about yourself...",
    "Save": "Save",
    "No bio provided": "No bio provided",
    // ArtisanDashboard
    "Artisan Dashboard": "Artisan Dashboard",
    "Sales Today": "Sales Today",
    "Manage Products": "Manage Products",
    "View Orders": "View Orders",
    "Failed to fetch dashboard stats. Please log in.": "Failed to fetch dashboard stats. Please log in.",
    // ArtisanComments
    "Comments on My Products": "Comments on My Products",
    "Comment": "Comment",
    "Product": "Product",
    "Product Deleted": "Product Deleted",
    "No comments found.": "No comments found.",
    "Failed to fetch comments.": "Failed to fetch comments.",
    // AddProduct
    "Add New Product": "አዲስ ምርት ያክሉ",
    "Name": "ስም",
    "Price (in Br)": "ዋጋ (በብር)",
    "Description": "መግለጫ",
    "Category": "ምድብ",
    "Stock": "ክምችት",
    "Image": "ምስል",
    "Adding Product...": "ምርት በመጨመር ላይ...",
    "Add Product": "ምርት ያክሉ",
    "Select a category": "ምድብ ይምረጡ",
    "All fields are required.": "ሁሉም መስኮች አስፈላጊ ናቸው።",
    "Price must be a positive number.": "ዋጋ አዎንታዊ ቁጥር መሆን አለበት።",
    "Stock cannot be negative.": "ክምችት አሉታዊ መሆን አይችልም።",
    "Please upload a valid image (JPEG, PNG, or GIF).": "እባክዎ ተቀባይነት ያለው ምስል ይስቀሉ (JPEG፣ PNG፣ ወይም GIF)።",
    "Session expired. Please log in again.": "ክፍለ ጊዜ ጊዜው አልፏል። እባክዎ እንደገና ይግቡ።",
    "Failed to insert product": "ምርትን መጨመር አልተሳካም",
    "Product added successfully!": "ምርት በተሳካ ሁኔታ ተጨምሯል!",
    // ProductManagement
    "Product Management": "የምርት አስተዳደር",
    "Edit Product": "ምርት አርትዕ",
    "Update Product": "ምርት ያዘምኑ",
    "Updating Product...": "ምርት በመዘመን ላይ...",
    "Image (optional)": "ምስል (አማራጭ)",
    "Please fill in all required fields.": "እባክዎ ሁሉንም አስፈላጊ መስኮች ይሙሉ።",
    "Failed to add product. Please log in.": "ምርትን መጨመር አልተሳካም። እባክዎ ይግቡ።",
    "Failed to delete product. Please log in.": "ምርትን መሰረዝ አልተሳካም። እባክዎ ይግቡ።",
    "Failed to update product. Please log in.": "ምርትን መዘመን አልተሳካም። እባክዎ ይግቡ።",
    "Please log in as an artisan to access this page.": "እባክዎ ይህን ገፅ ለመድረስ እንደ እጅ ጥበብ ባለሙያ ይግቡ።",
    "Go to Login": "ወደ መግቢያ ይሂዱ",
    // OrderManagement
    "Order Management": "የትዕዛዝ አስተዳደር",
    "Filter by Status:": "በሁኔታ ማጣሪያ:",
    "All": "ሁሉም",
    "Pending": "በመጠባበቅ ላይ",
    "Shipped": "ተልኳል",
    "Delivered": "ደርሷል",
    "Cancelled": "ተሰርዟል",
    "Customer": "ደንበኛ",
    "Total": "ድምር",
    "Order Date": "የትዕዛዝ ቀን",
    "Actions": "ተግባራት",
    "Unknown Customer": "ያልታወቀ ደንበኛ",
    "No orders found.": "ምንም ትዕዛዞች አልተገኙም።",
    "Order Details": "የትዕዛዝ ዝርዝሮች",
    "Order ID": "የትዕዛዝ መለያ",
    "Date": "ቀን",
    "Products": "ምርቶች",
    "Close": "ዝጋ",
    "Cancel": "መሰረዝ",
    "Ship": "መላክ",
    "Deliver": "መድረስ",
    "Failed to fetch orders. Please try again.": "ትዕዛዞችን መጫን አልተሳካም። እባክዎ እንደገና ይሞክሩ።",
    "Order not found or you don’t have permission to update it.": "ትዕዛዝ አልተገኘም ወይም ለመዘመን ፍቃድ የለዎትም።",
    "Failed to update order status.": "የትዕዛዝ ሁኔታን መዘመን አልተሳካም።",
    // NavbarArtisan
    "Artisan Portal": "የእጅ ጥበብ ባለሙያ መግቢያ",
    // ArtisanProfile
    "Artisan Profile": "የእጅ ጥበብ ባለሙያ መገለጫ",
    "Bio": "ሕይወት ታሪክ",
    "Tell us about yourself...": "ስለራስዎ ይንገሩን...",
    "Save": "ያስቀምጡ",
    "No bio provided": "ምንም ሕይወት ታሪክ አልተሰጠም",
    // ArtisanDashboard
    "Artisan Dashboard": "የእጅ ጥበብ ባለሙያ መቆጣጠሪያ",
    "Sales Today": "የዛሬ ሽያጮች",
    "Manage Products": "ምርቶችን ያስተዳድሩ",
    "View Orders": "ትዕዛዞችን ይመልከቱ",
    "Failed to fetch dashboard stats. Please log in.": "የመቆጣጠሪያ መረጃዎችን መጫን አልተሳካም። እባክዎ ይግቡ።",
    // ArtisanComments
    "Comments on My Products": "በምርቶቼ ላይ ያሉ አስተያየቶች",
    "Comment": "አስተያየት",
    "Product": "ምርት",
    "Product Deleted": "ምርት ተሰርዟል",
    "No comments found.": "ምንም አስተያየቶች አልተገኙም።",
    "Failed to fetch comments.": "አስተያየቶችን መጫን አልተሳካም።",
    "404: Page Not Found": "404: ገፅ አልተገኘም",
    "Comment Details": "የአስተያየት ዝርዝሮች",
    "Loading...": "በመጫን ላይ...",
    "Failed to fetch comment details.": "የአስተያየት ዝርዝሮችን መጫን አልተሳካም።",
    "Back to Comments": "ወደ አስተያየቶች ተመለስ",
    "Comment": "አስተያየት",
    "Product": "ምርት",
    "Deleted Product": "የተሰረዘ ምርት",
    "Date": "ቀን",
    "Invalid comment ID. Please select a valid comment.": "የማይሰራ የአስተያየት መለያ። እባክዎ ትክክለኛ አስተያየት ይምረጡ።",
    "My Comments": "የእኔ አስተያየቶች",
    "Add New Comment": "አዲስ አስተያየት ጨምር",
    "Loading comments...": "አስተያየቶችን በመጫን ላይ...",
    "Please log in as a customer to view your comments.": "እባክዎ እንደ ደንበኛ ይግቡ አስተያየቶችዎን ለመመልከት።",
    "Please log in to view your comments.": "እባክዎ ይግቡ አስተያየቶችዎን ለመመልከት።",
    "Retry": "እንደገና ሞክር",
    "Go to Login": "ወደ መግቢያ ሂድ",
    "Failed to fetch comments. Please ensure you are logged in.": "አስተያየቶችን መጫን አልተሳካም። እባክዎ መግባትዎን ያረጋግጡ።",
    "Actions": "ተግባራት",
    "View Details": "ዝርዝሮችን ተመልከት",
    "Deleting...": "በመሰረዝ ላይ...",
    "No comments found. Add one to get started!": "ምንም አስተያየቶች አልተገኙም። አንድ ጨምር ለመጀመር!",
    "Select Product": "ምርት ምረጥ",
    "Select a product": "አንድ ምርት ምረጥ",
    "Loading products...": "ምርቶችን በመጫን ላይ...",
    "Failed to fetch products for commenting.": "ለአስተያየት ምርቶችን መጫን አልተሳካም።",
    "No products available to comment on. Purchase something first!": "ለአስተያየት የሚገኙ ምርቶች የሉም። በመጀመሪያ ይግዙ!",
    "e.g., 'I need more of it'": "ለምሳሌ፣ 'ተጨማሪ እፈልጋለሁ'",
    "Cancel": "ይቅር",
    "Submitting...": "በመላክ ላይ...",
    "Please select a product.": "እባክዎ ምርት ይምረጡ።",
    "Please enter a comment.": "እባክዎ አስተያየት ያስገቡ።",
    "Failed to add comment. Please try again.": "አስተያየት መጨመር አልተሳካም። እባክዎ እንደገና ይሞክሩ።",
    "Authentication failed. Please log in again.": "ማረጋገጫ አልተሳካም። እባክዎ እንደገና ይግቡ።",
    "Are you sure you want to delete this comment?": "ይህን አስተያየት መሰረዝ እንደሚፈልጉ እርግጠኛ ነዎት?",
    "Failed to delete comment.": "አስተያየትን መሰረዝ አልተሳካም።",
    "Customer Dashboard": "የደንበኛ ዳሽቦርድ",
    "Loading dashboard...": "ዳሽቦርድ በመጫን ላይ...",
    "Failed to load dashboard data. Please log in.": "የዳሽቦርድ ውሂብ መጫን አልተሳካም። እባክዎ ይግቡ።",
    "Welcome back": "እንኳን ደህና መጡ",
    "Customer": "ደንበኛ",
    "Here’s what’s happening with your account.": "በመለያዎ ውስጥ ያለው እንቅስቃሴ ይኸው ነው።",
    "Recent Orders": "የቅርብ ጊዜ ትዕዛዞች",
    "Orders in the last 7 days": "ባለፉት 7 ቀናት ውስጥ ያሉ ትዕዛዞች",
    "View All Orders": "ሁሉንም ትዕዛዞች ተመልከት",
    "Profile": "መገለጫ",
    "Manage your personal details": "የግል ዝርዝሮችዎን ያስተዳድሩ",
    "Edit Profile": "መገለጫ አርትዕ",
    "Quick Actions": "ፈጣን ተግባራት",
    "Shop Now": "አሁን ግዛ",
    "View Cart": "ጋሪውን ተመልከት",
    "Order Details": "የትዕዛዝ ዝርዝሮች",
    "Loading order details...": "የትዕዛዝ ዝርዝሮችን በመጫን ላይ...",
    "Failed to fetch order details. Please try again.": "የትዕዛዝ ዝርዝሮችን መጫን አልተሳካም። እባክዎ እንደገና ይሞክሩ።",
    "Back to Orders": "ወደ ትዕዛዞች ተመለስ",
    "Order": "ትዕዛዝ",
    "Total Amount": "ጠቅላላ መጠን",
    "Order Status": "የትዕዛዝ ሁኔታ",
    "Payment Status": "የክፍያ ሁኔታ",
    "Order Date": "የትዕዛዝ ቀን",
    "Customer Information": "የደንበኛ መረጃ",
    "Email": "ኢሜይል",
    "Name": "ስም",
    "Phone": "ስልክ",
    "Products": "ምርቶች",
    "Product Name": "የምርት ስም",
    "Price": "ዋጋ",
    "Quantity": "ብዛት",
    "Total": "ጠቅላላ",
    "Pay Now": "አሁን ክፈል",
    "Pending": "በመጠባበቅ ላይ",
    "Shipped": "ተልኳል",
    "Cancelled": "ተሰርዟል",
    "Success": "ተሳክቷል",
    "Failed": "አልተሳካም",
    "Your Orders": "የእርስዎ ትዕዛዞች",
    "Loading orders...": "ትዕዛዞችን በመጫን ላይ...",
    "Failed to fetch orders. Please log in.": "ትዕዛዞችን መጫን አልተሳካም። እባክዎ ይግቡ።",
    "Order ID": "የትዕዛዝ መለያ",
    "No orders found.": "ምንም ትዕዛዞች አልተገኙም።",
    "Customer Profile": "የደንበኛ መገለጫ",
    "Loading profile...": "መገለጫን በመጫን ላይ...",
    "Failed to fetch profile. Please log in.": "መገለጫን መጫን አልተሳካም። እባክዎ ይግቡ።",
    "Profile Information": "የመገለጫ መረጃ",
    "Phone Number": "ስልክ ቁጥር",
    "Not set": "አልተዘጋጀም",
    "Change Password": "የይለፍ ቃል ቀይር",
    "Current Password": "የአሁኑ የይለፍ ቃል",
    "New Password": "አዲስ የይለፍ ቃል",
    "Confirm New Password": "አዲሱን የይለፍ ቃል አረጋግጥ",
    "Update Password": "የይለፍ ቃል ያዘምኑ",
    "Updating...": "በማዘመን ላይ...",
    "Failed to update profile. Please log in.": "መገለጫን ማዘመን አልተሳካም። እባክዎ ይግቡ።",
    "Save": "አስቀምጥ",
    "Saving...": "በማስቀመጥ ላይ...",
    "Phone number must be exactly 10 digits and contain only numbers.": "ስልክ ቁጥር 10 አሃዞች ብቻ መሆን አለበት እና ቁጥሮችን ብቻ መያዝ አለበት።",
    "Password must be at least 8 characters, with at least one uppercase letter, one lowercase letter, one number, and one special character (e.g., !@#$%^&*).": "የይለፍ ቃል ቢያንስ 8 ፊደሎች መሆን አለበት፣ ቢያንስ አንድ ትልቅ ፊደል፣ አንድ ትንሽ ፊደል፣ አንድ ቁጥር፣ እና አንድ ልዩ ቁምፊ (ለምሳሌ፣ !@#$%^&*)።",
    "New password and confirm password do not match.": "አዲስ የይለፍ ቃል እና የተረጋገጠ የይለፍ ቃል አይዛመዱም።",
    "Failed to update password.": "የይለፍ ቃልን ማዘመን አልተሳካም።",
    "Password updated successfully!": "የይለፍ ቃል በተሳካ ሁኔታ ተዘምኗል!",
    "Customer Portal": "የደንበኛ ፖርታል",
    "Dashboard": "ዳሽቦርድ",
    "Shop": "ግዛ",
    "Cart": "ጋሪ",
    "Orders": "ትዕዛዞች",
    "Comments": "አስተያየቶች",
    "Logout": "ውጣ"
  }
};

export const translateText = (text, language) => {
  return translations[language]?.[text] || text; // Fallback to original text if not found
};